# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83f02a42aabdf19a19c0f93ccd7bd9b3074159efeb4c35de24de0d9a421d67bd91809c102e0975d2ec79c6f53320c4ce086a1a5da815871ebf266d2581d900de
  MAIL_DOMAIN: smtp.gmail.com
  MAIL_USERNAME: sample@email.com
  MAIL_PASSWORD: password


test:
  secret_key_base: 0065b4e118d397bc263a6760c8af91b8f330a5d86d639e67609b5112a05f1eeaafa1f82152da60da64a979c0da1f56cde33d5311c235af066aba880074223a3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
